from logging import exception

try:
    z = int(input("Enter a number: "))
    if z > 0:
        print("positive")

